version: '3'
services:
  ionic:
    build:
      context: ../../
      dockerfile: tools/docker-compose/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - '8100:8100'
    tty: true
    stdin_open: true
